---
name: Check
on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags:
      - '*'
  pull_request:
jobs:
  runic:
    name: Runic formatting (Runic@${{ matrix.runic-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runic-version: ['1', '1.0', '1.0.1', 'master', '']
    steps:
      - uses: actions/checkout@v4
      # - uses: julia-actions/setup-julia@v2
      #   with:
      #     version: '1.11'
      - uses: julia-actions/cache@v2
      - uses: ./
        with:
          version: ${{ matrix.runic-version }}
  runic-format-files:
    name: Runic formatting suggestions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v2
      - run: echo "1+1" >> src/check.jl && grep -q "1+1" src/check.jl
      - uses: ./
        with:
          format_files: true
        continue-on-error: true
      - run: grep -q "1 + 1" src/check.jl
  runic-extensions:
    name: Runic markdown extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v2
      - run: |
          printf '```julia\n1+1\n```\n' > test.md
          git add test.md
          grep -q "1+1" test.md
      - uses: ./
        with:
          version: 'master'
          extensions: 'jl,md'
          format_files: true
        continue-on-error: true
      - run: grep -q "1 + 1" test.md
  runic-docstrings:
    name: Runic docstrings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v2
      - run: |
          printf '"""\n```julia\n1+1\n```\n"""\nfunction foo() end\n' > test.jl
          git add test.jl
          grep -q "1+1" test.jl
      - uses: ./
        with:
          version: 'master'
          docstrings: true
          format_files: true
        continue-on-error: true
      - run: grep -q "1 + 1" test.jl
